version: "3.7"

volumes:
  openstreetmap-data:
    external: true
  openstreetmap-rendered-tiles:

services:

  proxy:
    image: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    - ./tc-alphassl.crt:/etc/nginx/conf.d/domain.crt
    - ./tc-alphassl.key:/etc/nginx/conf.d/domain.key
    ports:
    - 0.0.0.0:80:80
    - 0.0.0.0:443:443
    depends_on:
    - osm
    restart: always
    logging:
      driver: gcplogs


  osm:
    image: overv/openstreetmap-tile-server
    command: run
    environment:
    - THREADS=24
    volumes:
    - openstreetmap-data:/var/lib/postgresql/12/main
    - openstreetmap-rendered-tiles:/var/lib/mod_tile
    shm_size: 128M
    restart: always
    logging:
      driver: gcplogs
