version: "3.7"

volumes:
  openstreetmap-data:
    external: true
  openstreetmap-rendered-tiles:

services:

  proxy:
    image: nginx
    volumes:
      - osm-data:/data/database/
    ports:
    - 0.0.0.0:80:80
    - 0.0.0.0:443:443
    depends_on:
    - osm
    restart: always
    logging:
      driver: gcplogs

volumes:
  osm-data:
    external: true

  osm:
    image: overv/openstreetmap-tile-server
    command: run
    environment:
    - THREADS=24
    volumes:
    - openstreetmap-data:/var/lib/postgresql/12/main
    - openstreetmap-rendered-tiles:/var/lib/mod_tile
    shm_size: 128M
    restart: always
    logging:
      driver: gcplogs
